# Despliegue final del modelo

Link de reporte completo: https://drive.google.com/file/d/1CPU3u-60y3_lVvC6SHrrmrnBZjvQg29_/view?usp=sharing

In [1]:
# Importar bibliotecas necesarias
import pandas as pd         # Para trabajar con datos tabulares
import numpy as np          # Para computación numérica
import matplotlib.pyplot as plt  # Para crear gráficos
import seaborn as sns       # Para crear gráficos más avanzados y análisis exploratorio de datos

# Importar bibliotecas adicionales para estadísticas y aprendizaje automático
from numpy import std        # Para calcular desviación estándar
from numpy import mean       # Para calcular media
from scipy import stats      # Para estadísticas
from pandas import read_csv  # Para leer datos desde un archivo CSV
from matplotlib import pyplot  # Para crear gráficos más avanzados
from collections import Counter  # Para contar elementos en una lista o arreglo
from sklearn import datasets  # Para cargar conjuntos de datos de muestra
from sklearn import metrics   # Para métricas de evaluación de modelos de aprendizaje automático
from scipy.stats import chi2_contingency   # Para pruebas de hipótesis estadísticas
from scipy.stats import contingency      # Para pruebas de hipótesis estadísticas
from imblearn.over_sampling import SMOTE  # Para equilibrar clases desbalanceadas en aprendizaje automático
from sklearn.tree import DecisionTreeClassifier  # Para árboles de decisión en aprendizaje automático
from sklearn.preprocessing import LabelEncoder  # Para codificar variables categóricas
from sklearn.model_selection import train_test_split  # Para dividir datos en conjuntos de entrenamiento y prueba
from sklearn.model_selection import cross_val_score  # Para validación cruzada
from sklearn.model_selection import RepeatedStratifiedKFold   # Para validación cruzada estratificada
from sklearn.model_selection import GridSearchCV  # Para ajuste de hiperparámetros en aprendizaje automático
from sklearn.model_selection import RandomizedSearchCV  # Para ajuste de hiperparámetros en aprendizaje automático
from sklearn.neighbors import KNeighborsClassifier  # Para clasificación basada en vecinos cercanos en aprendizaje automático
from sklearn.ensemble import RandomForestClassifier  # Para clasificación basada en bosques aleatorios en aprendizaje automático
from sklearn.neural_network import MLPClassifier  # Para clasificación basada en redes neuronales artificiales en aprendizaje automático
from sklearn.naive_bayes import GaussianNB  # Para clasificación basada en naive Bayes en aprendizaje automático
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix  # Para métricas de evaluación de modelos de aprendizaje automático

In [4]:
df= pd.read_csv('df_modelos.csv')
diccionario=pd.read_csv('diccionario2.csv')
df_nombres= pd.read_csv('df_nombres.csv')

data = df.values
# split into input and output elements
X, y = data[1:, :-1], data[1:, -1]
# label encode the target variable
y = LabelEncoder().fit_transform(y)
# transform the dataset
oversample = SMOTE(k_neighbors=4) 
X, y = oversample.fit_resample(X, y)
# summarize distribution
counter = Counter(y)
for k,v in counter.items():
 per = v / len(y) * 100

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
#Bosques Aleatorios
algoritmo = RandomForestClassifier(n_estimators = 100, criterion = 'entropy')
#Entreno el modelo
algoritmo.fit(X_train, y_train)
#Realizo una predicción
y_pred = algoritmo.predict(X_test)
#Calculo la exactitud del modelo
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

0.7571868583162218

In [8]:
leer_archivo = input("Por favor, escribe el nombre del archivo que quieres analizar: ")
archivo_predicciones=input("Por favor, escribe el nombre donde quieres guardar las predicciones: ")

Por favor, escribe el nombre del archivo que quieres analizar: prueba_1.csv
Por favor, escribe el nombre donde quieres guardar las predicciones: resultados

In [18]:
prueba_1=pd.read_csv(leer_archivo)
k=prueba_1.shape[1]
prueba_1

,PLANTAORIGEN_Pesqueria,D_CLIENTE,PESO_NETO,ESTADO,CIUDAD,TIPOTRANSPORTE,target,EMPRESA_TRANSPORTISTA
0,1,187,30670,1,39,9,20,TRANSPORTE31
1,1,107,36890,8,35,5,50,TRANSPORTE63
2,1,145,23300,14,61,6,39,TRANSPORTE52
3,1,147,20480,22,1,5,15,TRANSPORTE26
4,1,99,36980,1,39,5,40,TRANSPORTE53
...,...,...,...,...,...,...,...,...
126,1,99,28300,1,39,5,66,TRANSPORTE8
127,1,227,21240,14,42,5,57,TRANSPORTE70
128,1,28,34680,14,61,5,9,TRANSPORTE19
129,1,227,32620,14,42,6,52,TRANSPORTE66
130,1,145,38230,14,61,5,54,TRANSPORTE68

In [19]:

predicciones = pd.DataFrame(0, index=range(k), columns=['Prediccion1', 'Prediccion2', 'Prediccion3', 'Prediccion4', 'Prediccion5'])


for n in range(k):    
    v1=prueba_1.iloc[n,0]     
    v2=prueba_1.iloc[n,1] 
    v3=prueba_1.iloc[n,2] 
    v4=prueba_1.iloc[n,3] 
    v5=prueba_1.iloc[n,4] 
    v6=prueba_1.iloc[n,5]

    valores = [[v2,v2,v3,v4,v5,v6]]

    # Llamar a tu modelo para predecir con los valores de las variables

    probabilidades = algoritmo.predict_proba(valores)
    orden_probabilidades = np.argsort(probabilidades[0])[::-1]

    predicciones.iloc[n,0] =diccionario[ diccionario["Empresa_numerica"] == orden_probabilidades[0]].iloc[0,1]
    predicciones.iloc[n,1] =diccionario[ diccionario["Empresa_numerica"] == orden_probabilidades[1]].iloc[0,1]
    predicciones.iloc[n,2] =diccionario[ diccionario["Empresa_numerica"] == orden_probabilidades[2]].iloc[0,1]
    predicciones.iloc[n,3] =diccionario[ diccionario["Empresa_numerica"] == orden_probabilidades[3]].iloc[0,1]
    predicciones.iloc[n,4] =diccionario[ diccionario["Empresa_numerica"] == orden_probabilidades[4]].iloc[0,1]


prediccion= pd.concat([prueba, predicciones], axis=1)
prediccion

,PLANTAORIGEN_Pesqueria,D_CLIENTE,PESO_NETO,ESTADO,CIUDAD,TIPOTRANSPORTE,target,EMPRESA_TRANSPORTISTA,Prediccion1,Prediccion2,Prediccion3,Prediccion4,Prediccion5
0,1,187,30670,1,39,9,20,TRANSPORTE31,TRANSPORTE31,TRANSPORTE84,TRANSPORTE66,TRANSPORTE52,TRANSPORTE8
1,1,107,36890,8,35,5,50,TRANSPORTE63,TRANSPORTE63,TRANSPORTE75,TRANSPORTE46,TRANSPORTE8,TRANSPORTE61
2,1,145,23300,14,61,6,39,TRANSPORTE52,TRANSPORTE57,TRANSPORTE53,TRANSPORTE9,TRANSPORTE40,TRANSPORTE32
3,1,147,20480,22,1,5,15,TRANSPORTE26,TRANSPORTE26,TRANSPORTE75,TRANSPORTE9,TRANSPORTE3,TRANSPORTE31
4,1,99,36980,1,39,5,40,TRANSPORTE53,TRANSPORTE53,TRANSPORTE61,TRANSPORTE23,TRANSPORTE8,TRANSPORTE38
...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,1,99,28300,1,39,5,66,TRANSPORTE8,NaN,NaN,NaN,NaN,NaN
127,1,227,21240,14,42,5,57,TRANSPORTE70,NaN,NaN,NaN,NaN,NaN
128,1,28,34680,14,61,5,9,TRANSPORTE19,NaN,NaN,NaN,NaN,NaN
129,1,227,32620,14,42,6,52,TRANSPORTE66,NaN,NaN,NaN,NaN,NaN
130,1,145,38230,14,61,5,54,TRANSPORTE68,NaN,NaN,NaN,NaN,NaN